services:
  jupyter:
    build:
      context: .
    image: slim-jupyter-base
    container_name: ${CONTAINER_NAME}-gpu
    restart: always
    runtime: nvidia
    shm_size: ${CONTAINER_SHARED_MEMORY}
    environment:
      - NVIDIA_VISIBLE_DEVICES=${CONTAINER_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "${CONTAINER_GPU_PORT}:8888"
    volumes:
      - ${CONTAINER_WORKSPACE}:/workspace

  redis-deployment:
    image: redis:7.0
    ports:
      - "${CONTAINER_REDIS_DEPLOYMENT_PORT}:6379"
    volumes:
      - ${CONTAINER_DATASET_DEPLOYMENT}:/data

  redis-testing:
    image: redis:7.0
    ports:
      - "${CONTAINER_REDIS_TESTING_PORT}:6379"
    volumes:
      - ${CONTAINER_DATASET_TESTING}:/data