services:
  jupyter-gpu:
    build:
      context: .
    image: slim-jupyter-base
    container_name: ${CONTAINER_NAME}-gpu
    restart: always
    runtime: nvidia
    shm_size: ${CONTAINER_SHARED_MEMORY}
    environment:
      - NVIDIA_VISIBLE_DEVICES=${CONTAINER_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "${CONTAINER_PORT}:8888"
    volumes:
      - ${CONTAINER_WORKSPACE}:/workspace
    profiles:
      - gpu

  jupyter-cpu:
    build:
      context: .
    image: slim-jupyter-base
    container_name: ${CONTAINER_NAME}-cpu
    restart: always
    shm_size: ${CONTAINER_SHARED_MEMORY}
    environment: []
    ports:
      - "${CONTAINER_PORT}:8888"
    volumes:
      - ${CONTAINER_WORKSPACE}:/workspace
    profiles:
      - cpu
